"""GENERATED by tools/gen_config.py from config/snm_config.yaml -- DO NOT EDIT.

Generated parameter values for the SuperNeuroMAT3 FPGA host. Edit
config/snm_config.yaml and run `py tools/gen_config.py`, never this file.
HardwareSpec (snm_network) is built from these values.
"""

# logical capacity
N_MAX   = 1400
SYN_MAX = 32768

# datapath widths (bits)
DATA_W   = 16
WEIGHT_W = 8
REF_W    = 8
ACCUM_W  = 32

# STDP
STDP_T_MAX = 5

# streaming / FIFOs
EVENT_FIFO_DEPTH = 1400
DESC_FIFO_DEPTH  = 16
SPIKE_FIFO_DEPTH = 4

# transport
BAUD = 4000000

# board this bitstream was built for (key into config/boards.yaml)
BOARD = 'basys3'
FPGA_PART = 'xc7a35tcpg236-1'

# timing: as-built core clock (Hz), for converting on-chip tick cycles -> seconds
CORE_CLK_HZ = 100000000

# generated PHYSICAL memory depths (so host tools can display / sanity-check the
# actual sizes the bitstream was built with) and the structural neuron-count cap
CTRL_DEPTH = 8192
SYN_DEPTH  = 32768
MAX_SUPPORTED_NMAX = 1706

# derived
SPIKE_WORDS = 44   # 32-bit reads per 1-bit-per-neuron output frame

CONFIG = {
    "n_max": N_MAX, "syn_max": SYN_MAX, "data_w": DATA_W, "weight_w": WEIGHT_W,
    "ref_w": REF_W, "accum_w": ACCUM_W, "stdp_t_max": STDP_T_MAX,
    "event_fifo_depth": EVENT_FIFO_DEPTH, "desc_fifo_depth": DESC_FIFO_DEPTH,
    "spike_fifo_depth": SPIKE_FIFO_DEPTH, "baud": BAUD, "spike_words": SPIKE_WORDS,
    "ctrl_depth": CTRL_DEPTH, "syn_depth": SYN_DEPTH,
    "max_supported_nmax": MAX_SUPPORTED_NMAX, "board": BOARD, "fpga_part": FPGA_PART,
    "core_clk_hz": CORE_CLK_HZ,
}
