`timescale 1us/1ns
// GENERATED by tools/gen_config.py from config/snm_config.yaml -- DO NOT EDIT.

`ifndef SNM_CONFIG_VH
`define SNM_CONFIG_VH

`define SNM_RTL_PROTOCOL_VERSION 3
`define SNM_N_MAX                1400
`define SNM_SYN_MAX              32768
`define SNM_DATA_W               16
`define SNM_WEIGHT_W             8
`define SNM_REF_W                8
`define SNM_ACCUM_W              32
`define SNM_STDP_T_MAX           5
`define SNM_BAUD                 4000000
`define SNM_EVENT_FIFO_DEPTH     1400
`define SNM_DESC_FIFO_DEPTH      16
`define SNM_SPIKE_FIFO_DEPTH     4
`define SNM_SPIKE_FIFO_SHIFT     0
`define SNM_N_INDEX_W            11
`define SNM_N_COUNT_W            11
`define SNM_SYN_INDEX_W          15
`define SNM_SPIKE_WORDS          44
`define SNM_CTRL_DEPTH           8192
`define SNM_SYN_DEPTH            32768
`define SNM_MAX_SUPPORTED_NMAX   32426
`define SNM_SYN_MEM_ULTRA        1
`define SNM_SYN_BANK0_URAM       1
`define SNM_SYN_BANK0            32768
`define SNM_SYN_BANK1            32768
`define SNM_SYN_BANK2            32768

`endif // SNM_CONFIG_VH
