name: "Create Draft Release w/ Docs"

# deploy the documentation to GitHub Pages via an artifact
# does not create a branch or any commits

# define triggers
on:
  push:
    branches:
      - release-test
    tags:
      - "v*"
#   pull_request:
#     branches:
#       - main

jobs:

  # build the documentation
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    # - name: Setup Graphviz
    #   uses: ts-graphviz/setup-graphviz@v2

    - name: Set up Python  # use uv to install Python
      run: uv python install

    - name: Install superneuromat
      run: |
        uv venv venv
        . venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        echo VIRTUAL_ENV=$VIRTUAL_ENV >> $GITHUB_ENV
        uv pip install .[docs]
        echo $PATH
      # note: need to modify GITHUB_ENV path for the new venv to be used
      # as each run step is a new shell
    - name: List src directory for debugging
      run: |
         ls -R src
         echo $PATH
    - name: Verify installation
      run: |
        python -c "import sys; print(sys.exec_prefix)"
        python -c "import superneuromat; print(superneuromat.__version__)"
        uv pip list
        uv pip show superneuromat
    - name: Build HTML
      run: |
        cd docs
        ./single html
    - name: Add to archive
      run: |
        zip -r superneuromat-${{ github.ref_name }}-docs.zip docs/superneuromat-docs/build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: docs-release
      with:
        name: superneuromat-docs
        path: superneuromat-${{ github.ref_name }}-docs.zip
    - name: Upload pages artifacts
      uses: actions/upload-pages-artifact@v3
      id: docs-pages
      with:
        name: github-pages
        path: docs/superneuromat-docs/build/html/
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: docs/build/html

  # Deploy job
  draft-release:
    # Add a dependency to the build job
    needs: build-docs
    if: github.ref_type == 'tag'

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: superneuromat-docs

      - name: show files
        run: ls -lAR
      - name: Create Draft Release and attach artifacts
        id: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            superneuromat-${{ github.ref_name }}-docs.zip
          generate_release_notes: true
          fail_on_unmatched_files: true

  # Deploy job
  deploy-pages:
    # Add a dependency to the build job
    needs: build-docs
    # only deploy pages if not a test tag
    if: ${{! contains(github.ref_name, 'test')}}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.docs-pages.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: docs-pages
        uses: actions/deploy-pages@v4
