name: "Sphinx: Build HTML"

on:
  push:
    branches:
      - main
      - actions-test
    # tags:
    #   - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python3 -m pip install uv
        uv venv venv
        source venv/bin/activate
        uv pip install .[docs]
    - name: List src directory for debugging
      run: |
         ls -R src
    - name: Verify installation
      run: |
        pip show superneuromat
    - name: Build HTML
      run: |
        cd docs
        make html
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: deployment
      with:
        name: github-pages
        path: docs/superneuromat-docs/build/html/
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: docs/build/html

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4